version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gammu_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sms
      MYSQL_USER: smsuser
      MYSQL_PASSWORD: smspass
    volumes:
      - gammu_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - smsnet

  gammu_modem_1:
    image: tomaszrim/gammu
    container_name: gammu_modem_1
    restart: always
    privileged: true
    depends_on:
      - mysql
    devices:
       - /dev/ttyUSB0:/dev/ttyUSB0
       - /dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if00-port0:/dev/serial/by-id/usb-HUAWEI_Technology_HUAWEI_Mobile-if00-port0
    volumes:
      - ./configs/gammu_modem_1:/etc/gammu:ro
      - ./scripts:/usr/local/bin:ro
    environment:
      - TZ=Europe/Moscow
    networks:
      - smsnet

  gammu_modem_2:
    image: tomaszrim/gammu
    container_name: gammu_modem_2
    restart: always
    depends_on:
      - mysql
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - ./configs/gammu_modem_2:/etc/gammu:ro
      - ./scripts:/usr/local/bin:ro
    environment:
      - TZ=Europe/Moscow
    networks:
      - smsnet

volumes:
  gammu_mysql_data:

networks:
  smsnet:
    driver: bridge
